# Generated by Django 3.1 on 2020-08-22 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wooribank.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'SALE'), (1, 'LEADER'), (2, 'ADMIN')], default=wooribank.models.UserTypes['SALE'])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
