# Generated by Django 3.1 on 2020-08-23 07:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wooribank.loan.models


class Migration(migrations.Migration):

    dependencies = [
        ('wooribank', '0001_initial'),
        ('loan', '0002_auto_20200822_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninfo',
            name='admin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loaninfo',
            name='admin_approve_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loaninfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loaninfo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='loaninfo',
            name='leader',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loaninfo',
            name='leader_approve_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loaninfo',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='loaninfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'NEW'), (1, 'LEADER_REVIEW'), (2, 'LEADER_RETURN'), (3, 'LEADER_APPROVE'), (4, 'ADMIN_REVIEW'), (5, 'ADMIN_RETURN'), (6, 'COMPLETED')], default=wooribank.loan.models.LoanStatus['NEW']),
        ),
        migrations.AddField(
            model_name='loaninfo',
            name='type',
            field=models.IntegerField(choices=[(0, 'LOAN'), (1, 'CREDIT_CARD')], default=wooribank.loan.models.LoanTypes['LOAN']),
        ),
        migrations.AddField(
            model_name='loaninfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LoanInfoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(null=True)),
                ('user', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wooribank.userinfo')),
            ],
        ),
    ]
