# Generated by Django 3.1 on 2020-08-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20200823_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
